name: Build Clockwork

on:
  workflow_run:
    workflows: [Test Clockwork]
    types: [completed]

permissions:
  contents: read

concurrency:
  group: "build"
  cancel-in-progress: false

# TODO: Add jobs to build on Windows and macOS
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup V
        uses: vlang/setup-v@v1.4
        with:
          stable: true
      - name: Build
        run: v run . build.prod
      - name: Archive built executable
        uses: actions/upload-artifact@v4
        with:
          name: clockwork-linux
          path: build/clockwork
